/**
 * CANONICAL DATA SCHEMA SPECIFICATION
 * Định nghĩa chuẩn hóa thống nhất toàn bộ cấu trúc bảng dữ liệu và trường thông tin
 * cho tất cả tác vụ: Giao diện Web, Xuất Excel, Nhập Excel/CSV, Đồng bộ Google Drive 2 chiều, và Tải file mẫu.
 */

export interface ColumnDefinition {
  index: number;
  excelCol: string;
  key: string;
  header: string;
  dataType: 'string' | 'owner' | 'deposit_type' | 'percent' | 'money_million' | 'date' | 'integer' | 'empty';
  required: boolean;
  aliases: string[];
  description: string;
  example: string | number;
  width: number;
}

export const CANONICAL_COLUMNS: ColumnDefinition[] = [
  {
    index: 0,
    excelCol: 'A',
    key: 'bank',
    header: 'Ngân hàng',
    dataType: 'string',
    required: true,
    aliases: ['ngân hàng', 'bank', 'nh', 'tổ chức tín dụng', 'tên ngân hàng', 'mã nh', 'ngan hang'],
    description: 'Tên viết tắt hoặc mã ngân hàng (SEA, SHB, VCB, CTG, BIDV, TCB, VPB, MB, ACB, VIB, TPB, LPB, HDB, MSB, OCB, NAB, NCB, BVB, AGRI, SCB, PVB...)',
    example: 'SHB',
    width: 14,
  },
  {
    index: 1,
    excelCol: 'B',
    key: 'owner',
    header: 'Chủ sổ',
    dataType: 'owner',
    required: true,
    aliases: ['chủ sổ', 'người gửi', 'đứng tên', 'owner', 'chủ sở hữu', 'chủ', 'nguoi gui', 'chu so'],
    description: 'Người đứng tên sổ tiết kiệm (Chồng / Vợ hoặc tên người sở hữu). Tuyệt đối không để trống hoặc lẫn với lãi suất.',
    example: 'Chồng',
    width: 14,
  },
  {
    index: 2,
    excelCol: 'C',
    key: 'depositType',
    header: 'Hình thức',
    dataType: 'deposit_type',
    required: true,
    aliases: ['hình thức', 'loại sổ', 'kênh gửi', 'kênh', 'deposit type', 'type', 'hinh thuc', 'loai so'],
    description: 'Kênh gửi tiết kiệm: "Tại quầy" (Sổ giấy tại quầy giao dịch) hoặc "Online" (Ứng dụng/Web ngân hàng)',
    example: 'Tại quầy',
    width: 12,
  },
  {
    index: 3,
    excelCol: 'D',
    key: 'interestRate',
    header: 'Lãi suất',
    dataType: 'percent',
    required: true,
    aliases: ['lãi suất', 'lai suat', 'rate', 'lãi %', '%/năm', 'lãi suất %/năm'],
    description: 'Lãi suất %/năm (ví dụ: 6.55%, 6.80%, 7.40%, 8.20%).',
    example: '6,80%',
    width: 12,
  },
  {
    index: 4,
    excelCol: 'E',
    key: 'principal',
    header: 'Tiền gửi',
    dataType: 'money_million',
    required: true,
    aliases: ['tiền gửi', 'tiền gởi', 'số tiền', 'gốc', 'principal', 'amount', 'tien gui', 'tien goi', 'so tien'],
    description: 'Số tiền gốc gửi (Đơn vị: Triệu VNĐ trong bảng tính, ví dụ: 1100 = 1.100.000.000 VNĐ).',
    example: 1100,
    width: 14,
  },
  {
    index: 5,
    excelCol: 'F',
    key: 'startDate',
    header: 'Gửi',
    dataType: 'date',
    required: true,
    aliases: ['gửi', 'ngày gửi', 'ngày mở', 'start', 'start date', 'ngay gui', 'ngay mo'],
    description: 'Ngày mở sổ tiết kiệm (Định dạng: D/M/YYYY hoặc DD/MM/YYYY, ví dụ: 22/8/2025).',
    example: '22/8/2025',
    width: 14,
  },
  {
    index: 6,
    excelCol: 'G',
    key: 'maturityDate',
    header: 'Đáo hạn',
    dataType: 'date',
    required: true,
    aliases: ['đáo hạn', 'ngày đáo hạn', 'đến hạn', 'hạn', 'maturity', 'end date', 'dao han', 'ngay dao han'],
    description: 'Ngày đáo hạn sổ tiết kiệm (Định dạng: D/M/YYYY hoặc DD/MM/YYYY, ví dụ: 22/8/2026).',
    example: '22/8/2026',
    width: 14,
  },
  {
    index: 7,
    excelCol: 'H',
    key: 'termMonths',
    header: 'Kỳ',
    dataType: 'integer',
    required: true,
    aliases: ['kỳ', 'kỳ hạn', 'tháng', 'term', 'months', 'ky', 'ky han', 'so thang'],
    description: 'Kỳ hạn gửi tính theo số tháng (ví dụ: 1, 3, 6, 9, 12, 13, 18, 24, 36).',
    example: 12,
    width: 8,
  },
  {
    index: 8,
    excelCol: 'I',
    key: 'remainingTime',
    header: 'Thời gian còn',
    dataType: 'integer',
    required: false,
    aliases: ['thời gian còn', 'còn lại', 'số tháng còn', 'thoi gian con', 'con lai', 'thoi gian con lai'],
    description: 'Số tháng/số ngày còn lại đến hạn tính theo thời gian thực từ ngày hiện tại.',
    example: 8,
    width: 14,
  },
  {
    index: 9,
    excelCol: 'J',
    key: 'termInterest',
    header: 'Tiền lãi theo sổ',
    dataType: 'money_million',
    required: false,
    aliases: ['tiền lãi theo sổ', 'lãi theo sổ', 'lãi kỳ hạn', 'lãi trọn kỳ', 'tien lai theo so', 'lai theo so'],
    description: 'Tổng tiền lãi thực nhận khi giữ sổ đến ngày đáo hạn (Đơn vị: Triệu VNĐ).',
    example: 74.8,
    width: 18,
  },
  {
    index: 10,
    excelCol: 'K',
    key: 'annualInterest',
    header: 'Tiền lãi 1 năm',
    dataType: 'money_million',
    required: false,
    aliases: ['tiền lãi 1 năm', 'lãi 1 năm', 'lãi năm', 'lãi tương đương 1 năm', 'tien lai 1 nam', 'lai 1 nam'],
    description: 'Tiền lãi quy đổi tương đương theo 1 năm (Triệu VNĐ = Gốc × Lãi suất).',
    example: 74.8,
    width: 18,
  },
  {
    index: 11,
    excelCol: 'L',
    key: 'maturityMonthYear',
    header: 'Tháng đáo hạn',
    dataType: 'string',
    required: false,
    aliases: ['tháng đáo hạn', 'tháng/năm', 'tháng đến hạn', 'thang dao han', 'thang/nam'],
    description: 'Tháng và năm đáo hạn dạng MM/YY (ví dụ: 08/26, 09/26).',
    example: '08/26',
    width: 14,
  },
  {
    index: 12,
    excelCol: 'M',
    key: 'separator1',
    header: '',
    dataType: 'empty',
    required: false,
    aliases: [],
    description: 'Cột phân cách bảng phụ',
    example: '',
    width: 4,
  },
  {
    index: 13,
    excelCol: 'N',
    key: 'annualHistoryYear',
    header: 'Lãi hàng năm',
    dataType: 'integer',
    required: false,
    aliases: ['lãi hàng năm', 'năm lịch sử lãi', 'năm', 'lai hang nam', 'nam'],
    description: 'Bảng phụ: Năm thống kê lãi thực nhận trong quá khứ (ví dụ: 2021, 2022, 2023, 2024, 2025, 2026).',
    example: 2025,
    width: 14,
  },
  {
    index: 14,
    excelCol: 'O',
    key: 'annualHistoryAmount',
    header: 'Số tiền',
    dataType: 'money_million',
    required: false,
    aliases: ['số tiền', 'lãi nhận', 'tiền lãi năm', 'so tien', 'lai nhan'],
    description: 'Bảng phụ: Tổng số tiền lãi thực nhận trong năm tương ứng (Triệu VNĐ).',
    example: 2150,
    width: 12,
  },
  {
    index: 15,
    excelCol: 'P',
    key: 'separator2',
    header: '',
    dataType: 'empty',
    required: false,
    aliases: [],
    description: 'Cột phân cách bảng phụ',
    example: '',
    width: 4,
  },
  {
    index: 16,
    excelCol: 'Q',
    key: 'balanceHistoryYear',
    header: 'Số cuối năm',
    dataType: 'integer',
    required: false,
    aliases: ['số cuối năm', 'năm số dư', 'dư cuối năm', 'so cuoi nam', 'nam so du'],
    description: 'Bảng phụ: Năm thống kê số dư tổng tài sản tiết kiệm cuối năm (ví dụ: 2021, 2022, 2023, 2024, 2025, 2026).',
    example: 2025,
    width: 14,
  },
  {
    index: 17,
    excelCol: 'R',
    key: 'balanceHistoryAmount',
    header: 'Số tiền',
    dataType: 'money_million',
    required: false,
    aliases: ['số tiền', 'tổng số dư', 'gốc cuối năm', 'so tien', 'tong so du'],
    description: 'Bảng phụ: Tổng số dư gốc tiết kiệm vào ngày 31/12 của năm tương ứng (Triệu VNĐ).',
    example: 34500,
    width: 12,
  },
  {
    index: 18,
    excelCol: 'S',
    key: 'annualIncome',
    header: 'Thu nhập năm',
    dataType: 'money_million',
    required: false,
    aliases: ['thu nhập năm', 'thu nhập tích lũy', 'thu nhập', 'thu nhap nam', 'thu nhap'],
    description: 'Bảng phụ: Tổng thu nhập gia đình tăng thêm trong năm (Triệu VNĐ).',
    example: 3600,
    width: 16,
  },
  {
    index: 19,
    excelCol: 'T',
    key: 'separator3',
    header: '',
    dataType: 'empty',
    required: false,
    aliases: [],
    description: 'Cột phân cách bảng Nhật ký biến động',
    example: '',
    width: 4,
  },
  {
    index: 20,
    excelCol: 'U',
    key: 'activityId',
    header: 'ID biến động',
    dataType: 'string',
    required: false,
    aliases: ['id biến động', 'id', 'mã biến động'],
    description: 'Bảng phụ: Mã nhận diện duy nhất của nhật ký biến động',
    example: 'ADJ_1727000000000',
    width: 18,
  },
  {
    index: 21,
    excelCol: 'V',
    key: 'activityDate',
    header: 'Ngày biến động',
    dataType: 'date',
    required: false,
    aliases: ['ngày biến động', 'ngày tất toán', 'ngày thực hiện'],
    description: 'Bảng phụ: Ngày diễn ra biến động sổ (YYYY-MM-DD hoặc DD/MM/YYYY)',
    example: '22/09/2026',
    width: 14,
  },
  {
    index: 22,
    excelCol: 'W',
    key: 'activityType',
    header: 'Loại biến động',
    dataType: 'string',
    required: false,
    aliases: ['loại biến động', 'hình thức tất toán', 'loại giao dịch'],
    description: 'Bảng phụ: Mở sổ mới / Tất toán đúng hạn / Tất toán trước hạn / Tái tục sổ',
    example: 'Tất toán đúng hạn',
    width: 18,
  },
  {
    index: 23,
    excelCol: 'X',
    key: 'activityBookCode',
    header: 'Mã sổ',
    dataType: 'string',
    required: false,
    aliases: ['mã sổ', 'mã sổ tiết kiệm', 'book code'],
    description: 'Bảng phụ: Mã sổ phát sinh biến động',
    example: 'SHB-2609-1100',
    width: 16,
  },
  {
    index: 24,
    excelCol: 'Y',
    key: 'activityBank',
    header: 'Ngân hàng',
    dataType: 'string',
    required: false,
    aliases: ['ngân hàng', 'bank'],
    description: 'Bảng phụ: Ngân hàng quản lý sổ',
    example: 'SHB',
    width: 12,
  },
  {
    index: 25,
    excelCol: 'Z',
    key: 'activityOwner',
    header: 'Chủ sở hữu',
    dataType: 'owner',
    required: false,
    aliases: ['chủ sở hữu', 'chủ sổ', 'owner'],
    description: 'Bảng phụ: Chủ sở hữu đứng tên',
    example: 'Chồng',
    width: 14,
  },
  {
    index: 26,
    excelCol: 'AA',
    key: 'activityPrincipal',
    header: 'Tiền gốc',
    dataType: 'money_million',
    required: false,
    aliases: ['tiền gốc', 'số tiền gốc'],
    description: 'Bảng phụ: Tiền gốc của sổ (Triệu VNĐ)',
    example: 1100,
    width: 14,
  },
  {
    index: 27,
    excelCol: 'AB',
    key: 'activityInterest',
    header: 'Lãi thực nhận',
    dataType: 'money_million',
    required: false,
    aliases: ['lãi thực nhận', 'lãi chốt'],
    description: 'Bảng phụ: Tiền lãi chốt thực nhận (Triệu VNĐ)',
    example: 74.8,
    width: 14,
  },
  {
    index: 28,
    excelCol: 'AC',
    key: 'activityNote',
    header: 'Ghi chú',
    dataType: 'string',
    required: false,
    aliases: ['ghi chú', 'nội dung', 'lý do'],
    description: 'Bảng phụ: Ghi chú chi tiết biến động',
    example: 'Đã tất toán chuyển về tài khoản',
    width: 24,
  },
];

/**
 * Danh sách 19 tiêu đề cột chuẩn hóa của hệ thống
 */
export const STANDARDIZED_SHEET_HEADERS = CANONICAL_COLUMNS.map((col) => col.header);
